# Generated by Django 4.0.3 on 2022-03-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_family_detail_patient_disease_schedule_visit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='landmark',
            field=models.CharField(max_length=100),
        ),
    ]
